defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Sathiesh Kaliyugarasan
subtitle: Software engineer

# Side Menu Links
menu:
  - text: Research
    link: /
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

# Socialmedia Icons
social_icons:

  - name: github
    link: https://github.com/skaliy
    icon: fab fa-github-square

  - name: twitter
    link: https://www.twitter.com/skaliy3
    icon: fab fa-twitter

  - name: linkedin
    link: https://no.linkedin.com/in/satheshkumar-kaliyugarasan-75269711b
    icon: fab fa-linkedin


    
